.\" castreceiver
.TH "castreceiver" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
castreceiver \- manual page for castreceiver 0.0.0
.SH "SYNOPSIS"
.B castreceiver
.SH "DESCRIPTION"
A CLI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
castreceiver
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
