.TH "CASTRECEIVER" "1" "0.0.3" "K.D.Hedegr" "User Commands"
.SH "NAME"
CastReceiver
.br

.SH "DESCRIPTION"
CastReceiver
.br
.SS "USAGE:"
castreceiver [OPTION?] - CastReceiver
.br
.SS "HELP OPTIONS:"
\fB-h\fR, \fB--help\fR
.br
       Show help options
.br

.SS "APPLICATION OPTIONS:"
\fB-V\fR, \fB--version\fR
.br
       Output version information and exit
.br

\fB-f\fR, \fB--friendly-name\fR
.br
       Friendly name to advertise.
.br

\fB-e\fR, \fB--exit-on-stop\fR
.br
       Exit when file stopped.
.br

\fB-v\fR, \fB--verbose\fR
.br
       Show renderer details on start.
.br

